# Задача II.10.6 (ж)
##### Северилов Павел 674 группа

Решить методами Гаусса и Зейделя, найти  $\lambda_{min},  \lambda_{max}$, определить число обусловленности матрицы $μ = ||A||·||A^{(-1)}||$. Сделать печать невязок обоих методов. Указать критерий останова итераций метода Зейделя.

В пукте ж) система п. д) при a = 20.

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/10/417b0cd2893e7403e0bbaf5de562eacd.png"  width=500 height=400></p>

In [1]:
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go

### Составим систему

In [2]:
N = 100
a = 20

A = a*np.eye(N)
for i in range(N):
    for j in range(N):
        if (i > j) & (i - j < 5):
            A[i][j] = 1
        if (i < j) & (j - i < 5):
            A[i][j] = 1
            
b = [float(i+1) for i in range(N)]
mtrx = np.column_stack((A, b)) # расширенная матрица
mtrx

array([[ 20.,   1.,   1., ...,   0.,   0.,   1.],
       [  1.,  20.,   1., ...,   0.,   0.,   2.],
       [  1.,   1.,  20., ...,   0.,   0.,   3.],
       ...,
       [  0.,   0.,   0., ...,   1.,   1.,  98.],
       [  0.,   0.,   0., ...,  20.,   1.,  99.],
       [  0.,   0.,   0., ...,   1.,  20., 100.]])

Сразу вычислим число обусловленности и $\lambda_{min},  \lambda_{max}$

In [3]:
mu = np.linalg.cond(A) # число обусловленности
eigenv = np.linalg.eig(A)[0]
lambda_max = max(eigenv)
lambda_min = min(eigenv)

print('mu = %f\nlambda_min(A) = %f\nlambda_max(A) = %f' %(mu, lambda_min, lambda_max))

mu = 1.647395
lambda_min(A) = 16.979513
lambda_max(A) = 27.971963


## Метод Гаусса

In [4]:
# решение для верхнетреугольной матрицы
def solution(A, m):
    x = np.empty(m)
    for i in range(m-1, -1, -1): # итерируем в обратном порядке
        x[i] = A[i][m] / A[i][i]
        for j in range(i-1, -1, -1):
            A[j][m] -= A[j][i] * x[i]
    return x

#  A -- расширенная матрица
def gauss(A):
    m = len(A) # количество строк в A
    for k in range(m):
        #
        for i in range(k + 1, m):
            coef = A[i][k] / A[k][k]
            for j in range(k + 1, m + 1):
                A[i][j] -= A[k][j] * coef
            A[i][k] = 0
    return solution(A, m)

In [5]:
# проверим работоспособность функции на простом примере
matrix = [[1, 1, 1, 6],
          [1, -1, 2, 5],
          [2, -1, -1, -3]] # решение (1, 2, 3)
gauss(matrix)

array([1., 2., 3.])

In [6]:
gauss_solv = gauss(mtrx)
gauss_solv

array([0.02522065, 0.06656199, 0.10603713, 0.14363565, 0.17935233,
       0.21451454, 0.24997228, 0.28562803, 0.32138319, 0.35713861,
       0.39286498, 0.42857782, 0.46428757, 0.49999946, 0.53571352,
       0.57142822, 0.60714284, 0.64285722, 0.67857148, 0.71428573,
       0.74999999, 0.78571428, 0.82142857, 0.85714286, 0.89285714,
       0.92857143, 0.96428571, 1.        , 1.03571429, 1.07142857,
       1.10714286, 1.14285714, 1.17857143, 1.21428571, 1.25      ,
       1.28571429, 1.32142857, 1.35714286, 1.39285714, 1.42857143,
       1.46428571, 1.5       , 1.53571429, 1.57142857, 1.60714286,
       1.64285714, 1.67857143, 1.71428571, 1.75      , 1.78571429,
       1.82142857, 1.85714286, 1.89285714, 1.92857143, 1.96428571,
       2.        , 2.03571429, 2.07142857, 2.10714286, 2.14285714,
       2.17857143, 2.21428571, 2.25      , 2.28571429, 2.32142857,
       2.35714286, 2.39285714, 2.42857143, 2.46428571, 2.5       ,
       2.53571429, 2.57142858, 2.60714285, 2.64285711, 2.67857

## Метод Зейделя

In [7]:
ITERATION_LIMIT = 10000
eps = 1e-20

def seidel(A, b):
    n = len(A)
    x = [.0] * n
    x_new = np.zeros_like(x)
    for _ in range(ITERATION_LIMIT):
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if all(abs(x_new[i]-x[i]) < eps for i in range(n)):
            return x_new
        x = x_new

In [8]:
seidel_solv = seidel(A, b)
seidel_solv

array([0.01740811, 0.0580423 , 0.0968258 , 0.13372928, 0.16873661,
       0.20283875, 0.23725929, 0.27189924, 0.30665653, 0.34142771,
       0.37616552, 0.41088711, 0.44560436, 0.48032357, 0.51504541,
       0.54976808, 0.5844907 , 0.61921306, 0.65393525, 0.68865742,
       0.72337962, 0.75810184, 0.79282407, 0.8275463 , 0.86226852,
       0.89699074, 0.93171296, 0.96643519, 1.00115741, 1.03587963,
       1.07060185, 1.10532407, 1.1400463 , 1.17476852, 1.20949074,
       1.24421296, 1.27893519, 1.31365741, 1.34837963, 1.38310185,
       1.41782407, 1.4525463 , 1.48726852, 1.52199074, 1.55671296,
       1.59143519, 1.62615741, 1.66087963, 1.69560185, 1.73032407,
       1.7650463 , 1.79976852, 1.83449074, 1.86921296, 1.90393519,
       1.93865741, 1.97337963, 2.00810185, 2.04282407, 2.0775463 ,
       2.11226852, 2.14699074, 2.18171296, 2.21643519, 2.25115741,
       2.28587963, 2.32060185, 2.35532407, 2.3900463 , 2.42476852,
       2.45949074, 2.49421296, 2.52893519, 2.56365741, 2.59837

## Разница методов

In [9]:
trace0 = go.Scatter(y = gauss_solv,
                    x = [(i + 1) for i in range(N)],
                    mode = 'lines+markers',
                    name = 'Метод Гаусса'
                   )

trace1 = go.Scatter(y = seidel_solv,
                    x = [i+1 for i in range(N)],
                    mode = 'lines+markers',
                    name = 'Метод Зейделя'
                   )

data = [trace0, trace1]

layout = go.Layout(title = 'Полученные корни системы',
                   xaxis = dict(title = '$i$'),
                   yaxis = dict(title = '$x_i$')
                  )

#fig = dict(data=data, layout=layout)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

In [10]:
# Разность корней
difference = [a_i - b_i for a_i, b_i in zip(seidel_solv, gauss_solv)]

trace = go.Scatter(y = difference,
                   x = [(i + 1) for i in range(N)],
                   mode = 'lines+markers',
                   name = 'Разница корней'
                  )
data = [trace]

layout = go.Layout(title = 'Разница между корнями в методах',
                   xaxis = dict(title = 'i'),
                   yaxis = dict(title = 'Разница')
                  )

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

## Невязки

Для нашей системы невзяка вычисляется по формуле 
$r = b - Ax$

In [11]:
nevyaz_gauss = abs(np.array(b) - np.dot(A, gauss_solv))
nevyaz_seidel = abs(np.array(b) - np.dot(A, seidel_solv))
print('невзяки Гаусс = %s\n\n невзяки Зейдель = %s' %(nevyaz_gauss, nevyaz_seidel))

невзяки Гаусс = [1.11022302e-16 0.00000000e+00 4.44089210e-16 0.00000000e+00
 1.77635684e-15 0.00000000e+00 1.77635684e-15 1.77635684e-15
 0.00000000e+00 0.00000000e+00 1.77635684e-15 3.55271368e-15
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.55271368e-15
 0.00000000e+00 0.00000000e+00 3.55271368e-15 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.55271368e-15
 3.55271368e-15 0.00000000e+00 0.00000000e+00 3.55271368e-15
 0.00000000e+00 0.00000000e+00 3.55271368e-15 3.55271368e-15
 7.10542736e-15 7.10542736e-15 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.42108547e-14 7.10542736e-15 7.10542736e-15
 7.10542736e-15 7.10542736e-15 0.00000000e+00 0.00000000e+00
 0.00000000e+00 7.10542736e-15 7.10542736e-15 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.42108547e-14
 0.00000000e+00 0.00000000e+00 7.10542736e-15 0.00000000e+00
 1.42108547e-14 7.10542736e-15 7.10542736e-15 0.00000000e+00
 7.10542736e-15 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.42108

In [12]:
trace0 = go.Scatter(y = nevyaz_gauss,
                    x = [(i + 1) for i in range(N)],
                    mode = 'lines+markers',
                    name = 'Метод Гаусса'
                   )

trace1 = go.Scatter(y = nevyaz_seidel,
                    x = [i+1 for i in range(N)],
                    mode = 'lines+markers',
                    name = 'Метод Зейделя'
                   )

data = [trace0, trace1]

layout = go.Layout(title = 'Невязки',
                   xaxis = dict(title = '$i$'),
                   yaxis = dict(title = '$r$')
                  )

#fig = dict(data=data, layout=layout)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

Построим отдельно невязки метода Гаусса, т.к. на этом графике ничего не понятно

In [14]:
# Метод Гаусса
trace0 = go.Scatter(y = nevyaz_gauss,
                    x = [(i + 1) for i in range(N)],
                    mode = 'lines+markers',
                    name = 'Метод Гаусса'
                   )

data = [trace0]
layout = go.Layout(title = 'Невязки метода Гаусса',
                   xaxis = dict(title = '$i$'),
                   yaxis = dict(title = '$r$')
                  )

fig = go.Figure(data=data, layout=layout)
py.iplot(fig)

Вычислим среднюю ошибку

In [15]:
gaus_err = np.mean(nevyaz_gauss)
seid_err = np.mean(nevyaz_seidel)
print('gaus_err = %e\nseid_err = %f' %(gaus_err, seid_err))

gaus_err = 4.481970e-15
seid_err = 1.412086


Как видно из графиков, при увеличении индекса решения увеличивается ошибка. Самое большое различие в корнях методов имеется для 92 корня, для этого же выброса и самая большая невязка для метода Зейделя, что и вносит основной вклад в столь существенное отличие в результатах средней ошибки. К тому же очевидно из графика невязки, что невязки для метода Гаусса гораздо меньше